### ISSUE TITLE
Goole Map API key

### ISSUE THREAD

**Issue by odecharette** [fungio/FungioGoogleMapBundle#2]
Hi,

Thanks for this bundle ! I'm running SF3 and happy to be able to use IvoryGoogleMapBundle

1 problem, I get an error when loadgin the map : _Google Maps API error: MissingKeyMapError_
I've done only the first step of your documentation

I have seen this article, it's look like now, we need an API key. Where can I setup this key ??
http://googlegeodevelopers.blogspot.co.ke/2016/06/building-for-scale-updates-to-google.html

Thanks
Olivia

**Comment by fungio** [comment]
Hi @odecharette 
ApiKey support has been added in the https://github.com/fungio/fungio-google-map/commits/master repository.

To use this feature just do as follow:

`$this->get('fungio_google_map.map');`
`$map->setApiKey('YOUR_API_KEY');`

**Comment by odecharette** [comment]
working ! thanks !!

**Comment by fungio** [comment]
I've also added ApiKey support in config.yml 04d26b3 

``` yaml
fungio_google_map:
    map:
        # You own map class
        class: "My\Fucking\Map"

        #...

        # google map Api language, default en
        language: en

        # google Api key, (To generate one read: https://console.developers.google.com/flows/enableapi?apiid=maps_backend,geocoding_backend,directions_backend,distance_matrix_backend,elevation_backend,places_backend&keyType=CLIENT_SIDE&reusekey=true)
        api_key: YOUR_API_KEY
```
